### PR TITLE
Added ability to retrieve the beam attenuation for a given run.

### PR DESCRIPTION
**Pull request by fredericpoitevin**
Not tested yet but the idea is just:
```python
exp='mfxp23120'
run=19
psi = PsanaInterface(exp, run, 'epix10k2M')
pv_att = "MFX:ATT:COM:R_CUR"
psi.ds.env().epicsStore().value(pv_att)
```
which returns `0.10940339989647549` or 11% transmission.

### CODE REVIEW

**Comment by fredericpoitevin** [comment]
It has now been tested. Here is an example of how this could be useful.

# Step 1 - jump over every n events and keep their index
```python
nevt=0
nevt_mod=10

time_index = []

for t in tqdm(psi.times):
    if(nevt % nevt_mod == 0):
        evt = psi.runner.event(t)
        beam_energy_mJ   = psi.get_fee_gas_detector_energy_mJ_evt(evt)
        photon_energy_eV = psi.get_photon_energy_eV_evt(evt)
        if beam_energy_mJ is not None and photon_energy_eV is not None:
            time_index.append(nevt)
    nevt += 1
```

# Step 2 - for those events, record the beam and photon energies (in eV)
```python
Ebeam = []
Ephot = []
n_photons_incoming = []

for i in tqdm(time_index):
    evt = psi.runner.event(psi.times[i])
    beam_energy_mJ   = psi.get_fee_gas_detector_energy_mJ_evt(evt)
    photon_energy_eV = psi.get_photon_energy_eV_evt(evt)
    if beam_energy_mJ is not None and photon_energy_eV is not None:
        beam_energy_eV = beam_energy_mJ / 1.602e-16 
        beam_energy_eV *= psi.get_beam_transmission()
        Ebeam.append(beam_energy_eV)
        Ephot.append(photon_energy_eV)
```

# Step 3 - plot the number of incoming photons in each event
```python
fig, axs = plt.subplots(nrows=1,ncols=2, figsize=(8,4))
scatter = axs[0].scatter(time_index, np.array(Ebeam)/np.array(Ephot), 
                         s=2, c=Ephot, cmap='magma')
axs[0].set_xlabel('event index')
axs[0].set_ylabel('# of incoming photons')
axs[0].grid()

cax0 = fig.add_axes([0.2,0.3,0.2,0.02])
fig.colorbar(scatter, label='photon energy (eV)', 
             cax=cax0, orientation='horizontal')

hexbin = axs[1].hexbin(Ephot,Ebeam, mincnt=1, gridsize=20, cmap='Reds')
axs[1].set_xlabel('photon energy (eV)')
axs[1].set_ylabel('beam energy (eV)')
axs[1].yaxis.tick_right()

cax1 = fig.add_axes([0.6,0.3,0.2,0.02])
fig.colorbar(hexbin, label='# of events in bin', 
             cax=cax1, orientation='horizontal')

plt.show()
```
image

**Review by apeck12 — APPROVED** [review]
Who needs attenuation when you've got satisfaction?

Thanks for this feature -- looks great! My only question is whether the visuals should be added as routine plots output by the `run_analysis` task?

**Comment by fredericpoitevin** [comment]
Indeed! :D And thanks!

I think that's a good idea re:visuals, although maybe that could wait until we revisit things with plotly? Having the traces added to the current ones (with the same style) would be great though!

**Comment by fredericpoitevin** [comment]
Oh we actually have an issue open for that actually (#261).

Before we merge this then, I'll add to `run_analysis`:
- trace of beam energy (in mJ)
- trace of photon energy (in eV)
- trace of number of photons?

**Comment by apeck12** [comment]
Sounds fantastic, thanks! Or as a separate PR if you'd prefer to defer this to later / the post-plotly phase of btx?

**Pull request merged**
