### PR TITLE
lock file decorator

### PR DESCRIPTION
**Pull request by gadorlhiac**
Create a new module, ```ih5``` for utilities related to HDF5 files. The module is organized under a new ```io``` subpackage. The module currently includes a decorator for creating 'lock' files to handle concurrent write attempts of the same file. The decorator also implements a timeout functionality which will cease attempting to call the decorated function after a certain amount of time has passed.

Usage:
```py
from io.ih5 import lock_file

@lock_file('file_to_write.h5', timeout=2)
def my_write_function():
    print('Writing file.')

my_write_function() # Check if the lock file exists, create it if not, and call the function
```

### CODE REVIEW

**Review by fredericpoitevin — APPROVED** [review]
Excellent! Thanks @gadorlhiac this is a huge contribution. 

Small question: do we want a little sleep in the while loop or is the timeout enough?

**Comment by gadorlhiac** [comment]
That's a fair point. We can include a wait time so it isn't continuously attempting to write. I'm not really sure what a reasonable value would be. 500 ms, 1 s?

It would also be possible to include a number of retries instead of or in addition to the timeout. So the logic would be something like: try to write 5 times, if unsuccessful, break.

**Comment by fredericpoitevin** [comment]
I'm not sure what would be best but naively I'd say having a timeout of 5s and a sleep of 1s should do it?

**Comment by gadorlhiac** [comment]
@fredericpoitevin Added a ```wait``` parameter. The defaults are ```timeout = 5``` and ```wait = 0.5```, but other values can be passed to the function.

**Comment by fredericpoitevin** [comment]
Thanks Gabriel!

**Pull request merged**
