### PR TITLE
Automated documentation through doxygen

### PR DESCRIPTION
**Pull request by gadorlhiac**
Automatically generate documentation using doxygen. Modify docstrings and add additional comments with variable descriptions using doxygen keywords for better formatting.

### CODE REVIEW

**Comment by fredericpoitevin** [comment]
Thanks @gadorlhiac this looks interesting! 

What I like:
- a convenient way to explore the code (see screenshot below) but I get something similar with pycharm of vscode.
- it also displays the Markdown content nicely

My current worries:
- 571 files changed (!)
- the look and feel is a bit dated.
- unclear how this could be used for tutorial or more in-depths explanations.

That being said, I think it'd be worth trying to set it up as a GitHub Pages and see if we use it over time?

*Doxygen*
image
image

*Pycharm*
image

**Comment by fredericpoitevin** [comment]
Also @gadorlhiac a few requests when you have time:
- could you document how to run this?
- I could not find the pdf?

**Comment by gadorlhiac** [comment]
All very good points. It is slightly dated in style but as long as it is readable that doesn't bother me that much. Even if it mimics some features available in an IDE I think it is important to have this type of documentation available for users who may not be interested in cloning the repository and/or are not using those IDEs. Some users or people at LCLS will certainly be interested in running this themselves, and may encounter an error which can be solved by inspecting the code.

With regards to the file number there are a lot, but the number is doubled because I just added both the latex and html file sets which are complementary. Still a lot of files but it can be made fewer. There are specific settings for what content is created which are controlled in the `Doxyfile`  config file. HTML, RTF, latex, xml and man-page documentation can be created and there are options for how these are configured. I'll take a look and see if the file number can be reduced.

Not sure why the PDF wasn't created, but you're right, it's not there. I'll take a look into why.

Running the software (after installation) is straightforward. You create a doxygen config file within the top directory or can have doxygen create a template for you:
```
doxygen -g
```
then after editing the config file you just run doxygen with it as an argument
```
doxygen Doxyfile
```

**Comment by fredericpoitevin** [comment]
Good points on all accounts.

I'd suggest we go forward with c
- [ ] clarifying hat we want Doxygen to output
- [ ] creating the GH Pages website
- [ ] setting up a GH worfklow that updates the website whenever source code is changed

**Comment by gadorlhiac** [comment]
In terms of organization in line with your actionables I propose
- Generating HTML only, this can be stored in an output directory called "docs"
- We can publish the GH pages website from this directory
- There are GH Actions for doxygen generation and gh pages operations but I've never used this before

Do we want to do this from the main branch? Or publish from this doxy branch in the mean time? I am not sure if the extra files will be annoying for the automated btx:main uploads every night

**Comment by fredericpoitevin** [comment]
It's great, thanks Gabriel!

Yes doing it from this branch for now is good, for the reason you mention. Maybe we'll have a separate branch for the LCLS pulls at some point and then we can revisit the idea of having Doxygen on the main branch.

I'll get going with the GH Actions workflow.

**Comment by fredericpoitevin** [comment]
my bad I did not mean to merge... I removed `Doxyfile` and `docs/` in https://github.com/lcls-users/btx/commit/2f4a677c802d6ba07173327dcf9839e91e4f5dc8

**Comment by fredericpoitevin** [comment]
Alright, it's working now after some dirty back and forth.

Every time we push to main or merge a PR to main, `.github/workflows/doxygen.yml` will be triggered. That will essentially run `doxygen` and push the generated html files to the `doxy` branch, in the root directory.

GH Pages have been set up so that the root of the `doxy` branch is where we host https://lcls-users.github.io/btx/

**Pull request merged**
